//公共语言
window.l10n = {
	    'en-us': {
	        home: 'Home',
	        accounts:'My Account',
	        blocks:'Block',
	        browse:'Browse',
	        vote:'Vote',
	        transfer:'Transfer',
	        peers:'Peers',
	        about:'About',
	        switch_lg:'Switch language',
	        cn:'Simplified Chinese',
	        en:'English',
	        total_balance:'Total Balance(XAS)',
	        latest_height:'Latest Block Height',
	        version:'Version Information',
	        asch_detail:'Asch transaction details',
	        jubi_price:'Jubi Last Price (CNY)',
	        yuanbao_price:'Yuanbao Last Price (CNY)',
	        biduobao_price:'Biduobao Last Price (CNY)',
	        my_deal:'My deal',
	        //account
	        logout:'Logout',
	        account_information:'Account Information',
	        second_secret:'Second Secret',
	        basic_information:'Basic Information',
	        address:'Address',
	        public_key:'Public Key',
	        set_secondary_password:'Set secondary password',
	        password:'Password',
	        confirm:'Confirm',
	        secondary_prompt:'Make sure you saved a secondary password security <br> once lost <br> your property in Asch system will not be set back <br> secondary password required <span style = "font-weight: bold;"> 5XAS </span> fee',
	        submit:'Submit',
	        have_been_set:'You have already set the second secret',
	        //block
	        delegate_information:'Delegate Information',
	        total_revenue:'Total Revenue(XAS)',
	        ranking:'Ranking',
	        productivity:'Productivity',
	        approval_rate:'Approval Rate',
	        produced_blocks:'Produced Blocks',
	        switch_network:'Switch network',
	        own_server:'Own server',
	        default_domestic_server:'Default domestic server',
	        official_overseas_server:'Official overseas server',
	        community_server:'Community server',
	        //browse
	        latest_block:'Latest Block',
	        //vote
	        trustee_list:'Delegate List',
	        vote_record:'Vote Record',
	        who_voted:'My Voters',
	        //transfer
	        sender:'Sender',
	        recipient:'Recipient',
	        amount:'Amount',
	        fee:'Fee',
	        prompt:'Please make sure you send XAS to the correct address. This operation cannot be cancelled',
	        send:'send',
	        //peers
	        peer_list:'Peer List',
	        //about
	        attention:'Focus on Asch development community public number',
	        understand:'Learn about Asch latest developments',
	        version_number:'Version：v1.1.1',
	        declare:'The wallet is offered by the Asch community',
	        donation_address:'Community donation address:',
	        copy_address:'Copy address',
	        project_introduction:'ASCH Project Introduction',
	        upgraded_version:'ASCH system, upgraded version of the ETH！！！',
	        },
	    'zh-cn': {
	    	home: '首页',
	        accounts:'个人中心',
	        blocks:'区块生产',
	        browse:'区块浏览',
	        vote:'投票',
	        transfer:'转账',
	        peers:'节点',
	        about:'关于',
	        switch_lg:'切换语言',
	        cn:'简体中文',
	        en:'英语',
	        total_balance:'余额(XAS)',
	        latest_height:'最后区块高度',
	        version:'版本信息',
	        asch_detail:'Asch交易详情',
	        jubi_price:'聚币最新价(CNY)',
	        yuanbao_price:'元宝最新价(CNY)',
	        biduobao_price:'币多宝最新价(CNY)',
	        my_deal:'我的交易',
	        //account
	        logout:'注销',
	        account_information:'账户信息',
	        second_secret:'二级密码',
	        basic_information:'基本信息',
	        address:'地址',
	        public_key:'公钥',
	        set_secondary_password:'设置二级密码',
	        password:'密码',
	        confirm:'确认',
	        secondary_prompt:'请确定您已经安全保存了二级密码<br>一旦丢失<br>您在Asch系统中的财产将无法找回<br>设置二级密码需要<span style="font-weight: bold;">5XAS</span>手续费',
	        submit:'提交',
	        have_been_set:'您已经设置过二级密码',
	        //block
	        delegate_information:'受托人基本信息',
	        total_revenue:'总收益(XAS)',
	        ranking:'排名',
	        productivity:'生产率',
	        approval_rate:'得票率',
	        produced_blocks:'生产的区块',
	        switch_network:'切换网络',
	        own_server:'自己的服务器',
	        default_domestic_server:'默认国内服务器',
	        official_overseas_server:'官方海外服务器',
	        community_server:'开发社区服务器',
	        //browse
	        latest_block:'最新区块',
	        //vote
	        trustee_list:'受托人列表',
	        vote_record:'投票记录',
	        who_voted:'谁投了我',
	        //transfer
	        sender:'发送者',
	        recipient:'接受者',
	        amount:'金额',
	        fee:'费用',
	        prompt:'请确保您正在发送XAS给正确的地址<br/>本操作无法撤消',
	        send:'发送',
	        //peers
	        peer_list:'节点列表',
	        //about
	        attention:'关注Asch开发社区公众号',
	        understand:'了解Asch官方最新开发动态',
	        version_number:'版本：v1.1.1',
	        declare:'本钱包由Asch开发社区竭诚提供',
	        donation_address:'社区捐赠地址:',
	        copy_address:'复制地址',
	        project_introduction:'Asch项目介绍',
	        upgraded_version:'阿希（ASCH)系统，升级版的以太坊！！！',
	    }
	}

//打开页面加载
if(localStorage.language == 1){
    L10N.updateLang('zh-cn');
  }else{
    L10N.updateLang('en-us');
  }
 